// Kid-friendly answer lists. Any letters are accepted as guesses (no
// dictionary rejection — friendlier for a 6-year-old).

export const WORDS_3 = [
  'ant', 'arm', 'bag', 'bat', 'bed', 'bee', 'big', 'bin', 'box', 'bug',
  'bus', 'but', 'can', 'cap', 'car', 'cat', 'cow', 'cup', 'cut', 'dad',
  'day', 'den', 'dig', 'dot', 'ear', 'eat', 'egg', 'eye', 'fan', 'far',
  'fig', 'fin', 'fit', 'fix', 'fox', 'fun', 'gap', 'get', 'got', 'gum',
  'hat', 'hay', 'hen', 'hip', 'hit', 'hop', 'hot', 'hug', 'hut', 'ice',
  'jam', 'jar', 'jet', 'jug', 'kit', 'lap', 'law', 'leg', 'let', 'lip',
  'lit', 'log', 'lot', 'man', 'map', 'mat', 'met', 'mix', 'mop', 'mud',
  'mug', 'nap', 'net', 'new', 'not', 'now', 'nut', 'oak', 'owl', 'pan',
  'paw', 'pea', 'peg', 'pen', 'pet', 'pig', 'pin', 'pot', 'pup', 'ran',
  'rat', 'raw', 'red', 'rip', 'rug', 'run', 'sad', 'sat', 'saw', 'sea',
  'set', 'sip', 'sit', 'six', 'sun', 'tan', 'tap', 'tea', 'ten', 'tin',
  'top', 'toy', 'tub', 'van', 'vet', 'wax', 'web', 'wet', 'wig', 'win',
  'yes', 'zip', 'zoo',
]

export const WORDS_4 = [
  'ball', 'bear', 'bell', 'bird', 'blue', 'boat', 'book', 'cake', 'calm',
  'camp', 'card', 'care', 'cart', 'cave', 'chin', 'clap', 'claw', 'clay',
  'coat', 'cold', 'cook', 'cool', 'corn', 'crab', 'dark', 'deer', 'desk',
  'dice', 'dirt', 'dish', 'dive', 'door', 'down', 'draw', 'drum', 'duck',
  'dust', 'east', 'easy', 'exit', 'face', 'fact', 'fall', 'farm', 'fast',
  'fern', 'fire', 'fish', 'five', 'flag', 'flat', 'flip', 'flow', 'food',
  'foot', 'fork', 'fort', 'four', 'frog', 'game', 'gate', 'gift', 'girl',
  'give', 'glad', 'glow', 'goat', 'gold', 'golf', 'good', 'gray', 'grew',
  'grin', 'grow', 'hair', 'half', 'hand', 'hang', 'hard', 'harp', 'hawk',
  'head', 'hear', 'heat', 'help', 'herd', 'hero', 'hide', 'high', 'hill',
  'hive', 'hold', 'home', 'hope', 'horn', 'hose', 'huge', 'hunt', 'jump',
  'keep', 'kind', 'king', 'kite', 'knee', 'knew', 'knot', 'lake', 'lamb',
  'lamp', 'land', 'last', 'late', 'leaf', 'leap', 'left', 'lime', 'line',
  'lion', 'list', 'live', 'loaf', 'lock', 'long', 'look', 'loud', 'love',
  'luck', 'lump', 'made', 'mail', 'make', 'many', 'mask', 'mate', 'math',
  'meal', 'meat', 'melt', 'mice', 'mild', 'milk', 'mind', 'mine', 'mint',
  'miss', 'moon', 'most', 'moth', 'move', 'much', 'must', 'nail', 'name',
  'neat', 'nest', 'news', 'next', 'nice', 'nine', 'nose', 'note', 'oval',
  'oven', 'page', 'pail', 'pair', 'palm', 'park', 'part', 'path', 'peak',
  'pear', 'pick', 'pile', 'pine', 'pink', 'plan', 'play', 'plum', 'pond',
  'pony', 'pool', 'post', 'pull', 'push', 'quiz', 'race', 'rain', 'ramp',
  'read', 'rest', 'ride', 'ring', 'ripe', 'road', 'roar', 'rock', 'roll',
  'roof', 'room', 'root', 'rope', 'rose', 'ruby', 'rung', 'safe', 'sail',
  'salt', 'sand', 'save', 'seal', 'seed', 'seek', 'seen', 'self', 'sell',
  'send', 'ship', 'shoe', 'shop', 'show', 'side', 'sing', 'sink', 'size',
  'skip', 'sled', 'slow', 'snap', 'snow', 'sock', 'soft', 'song', 'soup',
  'spin', 'spot', 'star', 'stay', 'stem', 'step', 'stir', 'stop', 'sung',
  'swim', 'tail', 'take', 'tale', 'talk', 'tall', 'tame', 'tank', 'tape',
  'team', 'tear', 'tell', 'tent', 'tide', 'tidy', 'time', 'tiny', 'toad',
  'told', 'tone', 'took', 'tool', 'town', 'trap', 'tree', 'trip', 'tuck',
  'tune', 'turn', 'twin', 'vase', 'very', 'vest', 'view', 'vine', 'wait',
  'wake', 'walk', 'warm', 'wash', 'wave', 'wear', 'week', 'well', 'went',
  'west', 'whip', 'wide', 'wild', 'will', 'wind', 'wing', 'wink', 'wish',
  'wolf', 'wood', 'wool', 'word', 'wore', 'work', 'worm', 'yard', 'yarn',
  'year', 'zero',
]

export const WORDS_5 = [
  'about', 'after', 'again', 'apple', 'beach', 'begin', 'below', 'berry',
  'black', 'blast', 'bloom', 'board', 'brain', 'brave', 'bread', 'break',
  'brick', 'bring', 'brook', 'broom', 'brown', 'brush', 'bunny', 'cabin',
  'candy', 'carry', 'catch', 'chair', 'chalk', 'charm', 'chase', 'cheek',
  'cheer', 'chess', 'chick', 'child', 'clean', 'clear', 'climb', 'clock',
  'cloud', 'clown', 'coach', 'coast', 'count', 'crane', 'crawl', 'cream',
  'creek', 'crisp', 'crown', 'daisy', 'dance', 'dream', 'dress', 'drink',
  'eagle', 'early', 'earth', 'eight', 'enjoy', 'fairy', 'feast', 'fence',
  'field', 'first', 'flame', 'flash', 'float', 'flock', 'floor', 'flute',
  'found', 'fresh', 'frost', 'fruit', 'funny', 'giant', 'glass', 'globe',
  'grape', 'grass', 'green', 'group', 'happy', 'heart', 'hello', 'honey',
  'horse', 'house', 'jelly', 'juice', 'koala', 'large', 'laugh', 'learn',
  'lemon', 'light', 'lucky', 'lunch', 'magic', 'maple', 'march', 'money',
  'month', 'moose', 'mouse', 'music', 'night', 'north', 'ocean', 'otter',
  'paint', 'panda', 'party', 'peach', 'pearl', 'penny', 'piano', 'pilot',
  'pizza', 'plane', 'plant', 'plate', 'point', 'pouch', 'pound', 'power',
  'press', 'pride', 'prize', 'puppy', 'queen', 'quick', 'quiet', 'rainy',
  'raise', 'ranch', 'reach', 'ready', 'river', 'robin', 'rocky', 'round',
  'royal', 'scale', 'scarf', 'score', 'seven', 'shape', 'share', 'sharp',
  'sheep', 'shelf', 'shell', 'shine', 'shirt', 'shore', 'short', 'shout',
  'skate', 'skunk', 'sleep', 'slide', 'small', 'smart', 'smell', 'smile',
  'snack', 'snail', 'snake', 'sound', 'south', 'space', 'spark', 'speak',
  'spell', 'spend', 'spoon', 'sport', 'stack', 'stage', 'stair', 'stand',
  'start', 'steam', 'stick', 'still', 'sting', 'stone', 'store', 'storm',
  'story', 'sunny', 'sweet', 'swing', 'table', 'teach', 'thank', 'there',
  'thing', 'think', 'three', 'tiger', 'today', 'tooth', 'touch', 'towel',
  'tower', 'track', 'train', 'treat', 'truck', 'trunk', 'twist', 'under',
  'water', 'whale', 'wheat', 'wheel', 'white', 'whole', 'windy', 'witch',
  'world', 'would', 'young',
]
